### ISSUE TITLE
Help me with this error  I found while making patch file.

### ISSUE THREAD

**Issue by Pantomath1999** [chandrikadeb7/JPMorgan-Chase-Virtual-Internship#13]
error: pathspec 'Patch' did not match any file(s) known to git
error: pathspec 'File'' did not match any file(s) known to git
![image](https://user-images.githubusercontent.com/55140882/90667410-5b0ac800-e26c-11ea-9449-17147191b235.png)

**Comment by chandrikadeb7** [comment]
Please enter your github username and email ID correctly.
