### ISSUE TITLE
I am facing problems while creating a patch file for task 1, can you please help me out in this ?

### ISSUE THREAD

**Issue by Dilipsonavane** [chandrikadeb7/JPMorgan-Chase-Virtual-Internship#2]

**Comment by Dilipsonavane** [comment]
I completed task 1 of  JP Morgan but I am not able to generate that patch file, I read that pdf provided within it but from that pdf, I didn't get it. here I am providing the images of errors which I got on my command line while generating that patch file.
 
![JPM](https://user-images.githubusercontent.com/29897115/81897568-89756900-95d4-11ea-9bcb-cf6586ef8e4b.png)
![JPM](https://user-images.githubusercontent.com/29897115/81897570-8b3f2c80-95d4-11ea-812c-7620140cc4c0.png)

**Comment by chandrikadeb7** [comment]
> I completed task 1 of JP Morgan but I am not able to generate that patch file, I read that pdf provided within it but from that pdf, I didn't get it. here I am providing the images of errors which I got on my command line while generating that patch file.
> 
> ![JPM](https://user-images.githubusercontent.com/29897115/81897568-89756900-95d4-11ea-9bcb-cf6586ef8e4b.png)
> ![JPM](https://user-images.githubusercontent.com/29897115/81897570-8b3f2c80-95d4-11ea-812c-7620140cc4c0.png)

Hello. Please input your email in config user.email "dipusonavane@gmail.com"
and your name in config user.name "Dilip Sonavane".

You have just interchanged both. Hope this helps!

**Comment by Dilipsonavane** [comment]
Thank you, but now I entered correct mail and name still not getting the desired output
![jpm2](https://user-images.githubusercontent.com/29897115/81904908-9c426a80-95e1-11ea-8f1a-abd9dae842f2.png)

**Comment by chandrikadeb7** [comment]
Use double quotes in "Create patch file"

**Comment by Dilipsonavane** [comment]
That's not the issue, actually in user.name field we have to enter our GitHub account username and I don't know that before, So Thank You for your help.

**Comment by pratyushshri2359** [comment]
I am also getting similar issue despite using github username it continues.
![problrm](https://user-images.githubusercontent.com/47253449/89224543-45ec3300-d5f6-11ea-8562-3dcb1ec1b9af.jpeg)

**Comment by Shubham-evg** [comment]
I have created and done with all and when downloaded th zip file it doesn't contain any .patch file to upload
